### ISSUE TITLE
Compatibility matrix spec file with K8s v1.19.16 does not spin CPI and CSI Pods

### ISSUE THREAD

**Issue by rpanduranga** [vmware-tanzu/vsphere-kubernetes-drivers-operator#104]
**Issue/Feature Description:**
Compatibility matrix spec file with K8s v1.19.16 does not spin CPI and CSI Pos
E1122 10:18:09.565422       1 controller.go:302] controller-runtime/manager/controller/vdoconfig "msg"="Reconciler error" "error"="could not fetch compatible CPI version for vSphere version and k8s version " "name"="compat-matrix-config" "namespace"="vmware-system-vdo" "reconciler group"="vdo.vmware.com" "reconciler kind"="VDOConfig" 

**What type of Issue/Feature is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
/kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

**Why this fix/ feature is needed(give scenarios or use cases):**
CPI and CSI Pods are not created for the kubernetes v1.19.16

**How to reproduce, in case of a bug:**
Used the beta delivered compatibility matrix file and K8s v1.19.16

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by ridaz** [comment]
The compatibility matrix provided in beta version doesn't contain compatible CPI skew version for k8s 1.21 and hence the pods didn't get spawned.
We can consume [this](https://github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/releases/download/0.1.1/compatibility.yaml) matrix in order to fetch compatible CSI and CPI version
